USE [GD1C2023]
GO

CREATE TABLE LOS_CEBOLLITAS.BI_local
(
	ID_LOCAL INT NOT NULL,
	ID_DIRECCION INT,
	DESCRIPCION NVARCHAR(255),
	ID_TIPO INT,
	NOMBRE NVARCHAR(100),
	CATEGORIA NVARCHAR(50)
);

CREATE TABLE LOS_CEBOLLITAS.BI_tipo_reclamo
(
	ID_TIPO_RECLAMO INT NOT NULL,
	DESCRIPCION NVARCHAR(50)
);

CREATE TABLE LOS_CEBOLLITAS.BI_hechos_pedidos
(
	ID_LOCAL INT,
	ID_TIPO_LOCAL INT,
	ID_TIPO_MOVILIDAD INT,
	ID_TIEMPO INT,
	ID_DIA INT,
	ID_RANGO_HORARIO INT,
	ID_LOCALIDAD INT,
	ID_TIPO_MEDIO INT,
	ID_RANGO_ETARIO_USUARIO INT,
	ID_RANGO_ETARIO_REPARTIDOR INT,
	ID_ESTADO_PEDIDO INT,
	CANT_PEDIDO DECIMAL(18,2),
	DESVIO_PROMEDIO DECIMAL(18,2),
	MONTO_TOTAL DECIMAL(18,2),
	VALOR_PROMEDIO_ENVIO DECIMAL(18,2),
	MONTO_CUPONES DECIMAL(18,2),
	CALIFICACION DECIMAL(18,2),
	PORCENTAJE_ENTREGADOS DECIMAL(18,2)
);

CREATE TABLE LOS_CEBOLLITAS.BI_hechos_reclamos
(
	ID_LOCAL INT,
	ID_TIPO_RECLAMO INT,
	ID_TIPO_LOCAL INT,
	ID_TIPO_MOVILIDAD INT,
	ID_TIEMPO INT,
	ID_DIA INT,
	ID_RANGO_HORARIO INT,
	ID_LOCALIDAD INT,
	ID_TIPO_MEDIO INT,
	ID_RANGO_ETARIO_USUARIO INT,
	ID_RANGO_ETARIO_REPARTIDOR INT,
	ID_RANGO_ETARIO_OPERADOR INT,
	ID_ESTADO_RECLAMO INT,
	CANT_RECLAMOS DECIMAL(18,2),
	PROMEDIO_RESOLUCION DECIMAL(18,2),
	MONTO_GENERADO DECIMAL(18,2)
);

CREATE TABLE LOS_CEBOLLITAS.BI_hechos_mensajeria
(
	ID_TIPO_MOVILIDAD INT,
	ID_ESTADO_MENSAJERIA INT,
	ID_TIPO_PAQUETE INT,
	ID_TIEMPO INT,
	ID_DIA INT,
	ID_RANGO_HORARIO INT,
	ID_LOCALIDAD INT,
	ID_TIPO_MEDIO INT,
	ID_RANGO_ETARIO_USUARIO INT,
	ID_RANGO_ETARIO_REPARTIDOR INT,
	DESVIO_PROMEDIO DECIMAL(18,2),
	PORCENTAJE_ENTREGADOS DECIMAL(18,2),
	PROMEDIO_VALOR_ASEGURADO DECIMAL(18,2)
);


CREATE TABLE LOS_CEBOLLITAS.BI_tipo_local
(
	ID_TIPO_LOCAL INT NOT NULL,
	TIPO_LOCAL NVARCHAR(50),
);

CREATE TABLE LOS_CEBOLLITAS.BI_tipo_movilidad
(
	ID_TIPO_MOVILIDAD INT NOT NULL,
	TIPO_MOVILIDAD NVARCHAR(50)
);

CREATE TABLE LOS_CEBOLLITAS.BI_tipo_paquete
(
	ID_TIPO_PAQUETE INT NOT NULL,
	TIPO_PAQUETE NVARCHAR(50)
);

CREATE TABLE LOS_CEBOLLITAS.BI_tiempo
(
	ID_TIEMPO INT IDENTITY(1,1),
	MES INT,
	ANIO INT
);

CREATE TABLE LOS_CEBOLLITAS.BI_dia
(
	ID_DIA INT NOT NULL,
	DIA NVARCHAR(50),
);

CREATE TABLE LOS_CEBOLLITAS.BI_rango_horario
(
	ID_RANGO_HORARIO INT NOT NULL,
	RANGO_HORARIO NVARCHAR(50),
);

CREATE TABLE LOS_CEBOLLITAS.BI_localidad
(
	ID_LOCALIDAD INT NOT NULL,
	NOMBRE NVARCHAR(100),
	PROVINCIA NVARCHAR(100)
);

CREATE TABLE LOS_CEBOLLITAS.BI_tipo_medio_pago
(
	ID_TIPO_MEDIO INT NOT NULL,
	TIPO_MEDIO_PAGO NVARCHAR(50),
);

CREATE TABLE LOS_CEBOLLITAS.BI_rango_etario
(
	ID_RANGO_ETARIO INT NOT NULL,
	RANGO_ETARIO NVARCHAR(50),
);

CREATE TABLE LOS_CEBOLLITAS.BI_estado_pedido
(
	ID_ESTADO_PEDIDO INT NOT NULL,
	ESTADO_PEDIDO NVARCHAR(50),
);

CREATE TABLE LOS_CEBOLLITAS.BI_estado_reclamo
(
	ID_ESTADO_RECLAMO INT IDENTITY(1,1),
	ESTADO_RECLAMO NVARCHAR(50),
);

CREATE TABLE LOS_CEBOLLITAS.BI_estado_mensajeria
(
	ID_ESTADO_MENSAJERIA INT NOT NULL,
	ESTADO_MENSAJERIA NVARCHAR(50),
);

--AGREGAMOS PK's y FK's

ALTER TABLE LOS_CEBOLLITAS.BI_local ADD CONSTRAINT pk_local_bi PRIMARY KEY (ID_LOCAL);
ALTER TABLE LOS_CEBOLLITAS.BI_tipo_local ADD CONSTRAINT pk_tipo_local_bi PRIMARY KEY (ID_TIPO_LOCAL);
ALTER TABLE LOS_CEBOLLITAS.BI_estado_mensajeria ADD CONSTRAINT pk_estado_msj_bi PRIMARY KEY (ID_ESTADO_MENSAJERIA);
ALTER TABLE LOS_CEBOLLITAS.BI_estado_reclamo ADD CONSTRAINT pk_estado_reclamo_bi PRIMARY KEY (ID_ESTADO_RECLAMO);
ALTER TABLE LOS_CEBOLLITAS.BI_estado_pedido ADD CONSTRAINT pk_estado_pedido_bi PRIMARY KEY (ID_ESTADO_PEDIDO);
ALTER TABLE LOS_CEBOLLITAS.BI_rango_etario ADD CONSTRAINT pk_rango_etario_bi PRIMARY KEY (ID_RANGO_ETARIO);
ALTER TABLE LOS_CEBOLLITAS.BI_tipo_medio_pago ADD CONSTRAINT pk_tipo_pago_bi PRIMARY KEY (ID_TIPO_MEDIO);
ALTER TABLE LOS_CEBOLLITAS.BI_localidad ADD CONSTRAINT pk_localidad_bi PRIMARY KEY (ID_LOCALIDAD);
ALTER TABLE LOS_CEBOLLITAS.BI_rango_horario ADD CONSTRAINT pk_rango_horario_bi PRIMARY KEY (ID_RANGO_HORARIO);
ALTER TABLE LOS_CEBOLLITAS.BI_dia ADD CONSTRAINT pk_dia_bi PRIMARY KEY (ID_DIA);
ALTER TABLE LOS_CEBOLLITAS.BI_tiempo ADD CONSTRAINT pk_tiempo_bi PRIMARY KEY (ID_TIEMPO);
ALTER TABLE LOS_CEBOLLITAS.BI_tipo_paquete ADD CONSTRAINT pk_tipo_paquete_bi PRIMARY KEY (ID_TIPO_PAQUETE);
ALTER TABLE LOS_CEBOLLITAS.BI_tipo_movilidad ADD CONSTRAINT pk_tipo_movilidad_bi PRIMARY KEY (ID_TIPO_MOVILIDAD);
ALTER TABLE LOS_CEBOLLITAS.BI_tipo_reclamo ADD CONSTRAINT pk_tipo_reclamo_bi PRIMARY KEY (ID_TIPO_RECLAMO);

ALTER TABLE LOS_CEBOLLITAS.BI_hechos_pedidos ADD CONSTRAINT fk_hechos_local FOREIGN KEY (ID_LOCAL) REFERENCES LOS_CEBOLLITAS.BI_local (ID_LOCAL);
ALTER TABLE LOS_CEBOLLITAS.BI_hechos_pedidos ADD CONSTRAINT fk_hechos_tipo_local FOREIGN KEY (ID_TIPO_LOCAL) REFERENCES LOS_CEBOLLITAS.BI_tipo_local (ID_TIPO_LOCAL);
ALTER TABLE LOS_CEBOLLITAS.BI_hechos_pedidos ADD CONSTRAINT fk_hechos_estado_pedido FOREIGN KEY (ID_ESTADO_PEDIDO) REFERENCES LOS_CEBOLLITAS.BI_estado_pedido (ID_ESTADO_PEDIDO);
ALTER TABLE LOS_CEBOLLITAS.BI_hechos_pedidos ADD CONSTRAINT fk_hechos_rango_etario_usuario FOREIGN KEY (ID_RANGO_ETARIO_USUARIO) REFERENCES LOS_CEBOLLITAS.BI_rango_etario (ID_RANGO_ETARIO);
ALTER TABLE LOS_CEBOLLITAS.BI_hechos_pedidos ADD CONSTRAINT fk_hechos_rango_etario_repartidor FOREIGN KEY (ID_RANGO_ETARIO_REPARTIDOR) REFERENCES LOS_CEBOLLITAS.BI_rango_etario (ID_RANGO_ETARIO);
ALTER TABLE LOS_CEBOLLITAS.BI_hechos_pedidos ADD CONSTRAINT fk_hechos_tipo_pago FOREIGN KEY (ID_TIPO_MEDIO) REFERENCES LOS_CEBOLLITAS.BI_tipo_medio_pago (ID_TIPO_MEDIO);
ALTER TABLE LOS_CEBOLLITAS.BI_hechos_pedidos ADD CONSTRAINT fk_hechos_localidad FOREIGN KEY (ID_LOCALIDAD) REFERENCES LOS_CEBOLLITAS.BI_localidad (ID_LOCALIDAD);
ALTER TABLE LOS_CEBOLLITAS.BI_hechos_pedidos ADD CONSTRAINT fk_hechos_rango_horario FOREIGN KEY (ID_RANGO_HORARIO) REFERENCES LOS_CEBOLLITAS.BI_rango_horario (ID_RANGO_HORARIO);
ALTER TABLE LOS_CEBOLLITAS.BI_hechos_pedidos ADD CONSTRAINT fk_hechos_dia FOREIGN KEY (ID_DIA) REFERENCES LOS_CEBOLLITAS.BI_dia (ID_DIA);
ALTER TABLE LOS_CEBOLLITAS.BI_hechos_pedidos ADD CONSTRAINT fk_hechos_tiempo FOREIGN KEY (ID_TIEMPO) REFERENCES LOS_CEBOLLITAS.BI_tiempo (ID_TIEMPO);
ALTER TABLE LOS_CEBOLLITAS.BI_hechos_pedidos ADD CONSTRAINT fk_hechos_tipo_movilidad FOREIGN KEY (ID_TIPO_MOVILIDAD) REFERENCES LOS_CEBOLLITAS.BI_tipo_movilidad (ID_TIPO_MOVILIDAD);

ALTER TABLE LOS_CEBOLLITAS.BI_hechos_reclamos ADD CONSTRAINT fk_hechos_rcl_local FOREIGN KEY (ID_LOCAL) REFERENCES LOS_CEBOLLITAS.BI_local (ID_LOCAL);
ALTER TABLE LOS_CEBOLLITAS.BI_hechos_reclamos ADD CONSTRAINT fk_hechos_rcl_tipo_reclamo FOREIGN KEY (ID_TIPO_RECLAMO) REFERENCES LOS_CEBOLLITAS.BI_tipo_reclamo (ID_TIPO_RECLAMO);
ALTER TABLE LOS_CEBOLLITAS.BI_hechos_reclamos ADD CONSTRAINT fk_hechos_rcl_tipo_mov FOREIGN KEY (ID_TIPO_MOVILIDAD) REFERENCES LOS_CEBOLLITAS.BI_tipo_movilidad (ID_TIPO_MOVILIDAD);
ALTER TABLE LOS_CEBOLLITAS.BI_hechos_reclamos ADD CONSTRAINT fk_hechos_rcl_tipo_local FOREIGN KEY (ID_TIPO_LOCAL) REFERENCES LOS_CEBOLLITAS.BI_tipo_local (ID_TIPO_LOCAL);
ALTER TABLE LOS_CEBOLLITAS.BI_hechos_reclamos ADD CONSTRAINT fk_hechos_rcl_tiempo FOREIGN KEY (ID_TIEMPO) REFERENCES LOS_CEBOLLITAS.BI_tiempo (ID_TIEMPO);
ALTER TABLE LOS_CEBOLLITAS.BI_hechos_reclamos ADD CONSTRAINT fk_hechos_rcl_dia FOREIGN KEY (ID_DIA) REFERENCES LOS_CEBOLLITAS.BI_dia (ID_DIA);
ALTER TABLE LOS_CEBOLLITAS.BI_hechos_reclamos ADD CONSTRAINT fk_hechos_rcl_rango_horario FOREIGN KEY (ID_RANGO_HORARIO) REFERENCES LOS_CEBOLLITAS.BI_rango_horario (ID_RANGO_HORARIO);
ALTER TABLE LOS_CEBOLLITAS.BI_hechos_reclamos ADD CONSTRAINT fk_hechos_rcl_localidad FOREIGN KEY (ID_LOCALIDAD) REFERENCES LOS_CEBOLLITAS.BI_localidad (ID_LOCALIDAD);
ALTER TABLE LOS_CEBOLLITAS.BI_hechos_reclamos ADD CONSTRAINT fk_hechos_rcl_tipo_pago FOREIGN KEY (ID_TIPO_MEDIO) REFERENCES LOS_CEBOLLITAS.BI_tipo_medio_pago (ID_TIPO_MEDIO);
ALTER TABLE LOS_CEBOLLITAS.BI_hechos_reclamos ADD CONSTRAINT fk_hechos_rcl_etario_usuario FOREIGN KEY (ID_RANGO_ETARIO_USUARIO) REFERENCES LOS_CEBOLLITAS.BI_rango_etario (ID_RANGO_ETARIO);
ALTER TABLE LOS_CEBOLLITAS.BI_hechos_reclamos ADD CONSTRAINT fk_hechos_rcl_etario_repartidor FOREIGN KEY (ID_RANGO_ETARIO_REPARTIDOR) REFERENCES LOS_CEBOLLITAS.BI_rango_etario (ID_RANGO_ETARIO);
ALTER TABLE LOS_CEBOLLITAS.BI_hechos_reclamos ADD CONSTRAINT fk_hechos_rcl_etario_operador FOREIGN KEY (ID_RANGO_ETARIO_OPERADOR) REFERENCES LOS_CEBOLLITAS.BI_rango_etario (ID_RANGO_ETARIO);
ALTER TABLE LOS_CEBOLLITAS.BI_hechos_reclamos ADD CONSTRAINT fk_hechos_rcl_estado FOREIGN KEY (ID_ESTADO_RECLAMO) REFERENCES LOS_CEBOLLITAS.BI_estado_reclamo (ID_ESTADO_RECLAMO);

ALTER TABLE LOS_CEBOLLITAS.BI_hechos_mensajeria ADD CONSTRAINT fk_hechos_msj_estado_msj FOREIGN KEY (ID_ESTADO_MENSAJERIA) REFERENCES LOS_CEBOLLITAS.BI_estado_mensajeria (ID_ESTADO_MENSAJERIA);
ALTER TABLE LOS_CEBOLLITAS.BI_hechos_mensajeria ADD CONSTRAINT fk_hechos_msj_rango_etario_usuario FOREIGN KEY (ID_RANGO_ETARIO_USUARIO) REFERENCES LOS_CEBOLLITAS.BI_rango_etario (ID_RANGO_ETARIO);
ALTER TABLE LOS_CEBOLLITAS.BI_hechos_mensajeria ADD CONSTRAINT fk_hechos_msj_rango_etario_repartidor FOREIGN KEY (ID_RANGO_ETARIO_REPARTIDOR) REFERENCES LOS_CEBOLLITAS.BI_rango_etario (ID_RANGO_ETARIO);
ALTER TABLE LOS_CEBOLLITAS.BI_hechos_mensajeria ADD CONSTRAINT fk_hechos_msj_tipo_pago FOREIGN KEY (ID_TIPO_MEDIO) REFERENCES LOS_CEBOLLITAS.BI_tipo_medio_pago (ID_TIPO_MEDIO);
ALTER TABLE LOS_CEBOLLITAS.BI_hechos_mensajeria ADD CONSTRAINT fk_hechos_msj_localidad FOREIGN KEY (ID_LOCALIDAD) REFERENCES LOS_CEBOLLITAS.BI_localidad (ID_LOCALIDAD);
ALTER TABLE LOS_CEBOLLITAS.BI_hechos_mensajeria ADD CONSTRAINT fk_hechos_msj_rango_horario FOREIGN KEY (ID_RANGO_HORARIO) REFERENCES LOS_CEBOLLITAS.BI_rango_horario (ID_RANGO_HORARIO);
ALTER TABLE LOS_CEBOLLITAS.BI_hechos_mensajeria ADD CONSTRAINT fk_hechos_msj_dia FOREIGN KEY (ID_DIA) REFERENCES LOS_CEBOLLITAS.BI_dia (ID_DIA);
ALTER TABLE LOS_CEBOLLITAS.BI_hechos_mensajeria ADD CONSTRAINT fk_hechos_msj_tiempo FOREIGN KEY (ID_TIEMPO) REFERENCES LOS_CEBOLLITAS.BI_tiempo (ID_TIEMPO);
ALTER TABLE LOS_CEBOLLITAS.BI_hechos_mensajeria ADD CONSTRAINT fk_hechos_msj_tipo_paquete FOREIGN KEY (ID_TIPO_PAQUETE) REFERENCES LOS_CEBOLLITAS.BI_tipo_paquete (ID_TIPO_PAQUETE);
ALTER TABLE LOS_CEBOLLITAS.BI_hechos_mensajeria ADD CONSTRAINT fk_hechos_msj_tipo_movilidad FOREIGN KEY (ID_TIPO_MOVILIDAD) REFERENCES LOS_CEBOLLITAS.BI_tipo_movilidad (ID_TIPO_MOVILIDAD);

GO

ALTER PROCEDURE LOS_CEBOLLITAS.MigrarDatosBI
AS
BEGIN

INSERT INTO LOS_CEBOLLITAS.BI_local SELECT * FROM LOS_CEBOLLITAS.local

INSERT INTO LOS_CEBOLLITAS.BI_tipo_local SELECT * FROM LOS_CEBOLLITAS.tipo_local

INSERT INTO LOS_CEBOLLITAS.BI_estado_mensajeria SELECT * FROM LOS_CEBOLLITAS.tipo_estado_mensajeria

INSERT INTO LOS_CEBOLLITAS.BI_estado_pedido SELECT * FROM LOS_CEBOLLITAS.tipo_estado_pedido

INSERT INTO LOS_CEBOLLITAS.BI_tipo_medio_pago SELECT * FROM LOS_CEBOLLITAS.tipo_pago

INSERT INTO LOS_CEBOLLITAS.BI_tipo_movilidad SELECT * FROM LOS_CEBOLLITAS.tipo_movilidad

INSERT INTO LOS_CEBOLLITAS.BI_tipo_paquete (ID_TIPO_PAQUETE,TIPO_PAQUETE) SELECT TIPO_PAQUETE,TIPO FROM LOS_CEBOLLITAS.tipo_paquete

INSERT INTO LOS_CEBOLLITAS.BI_tipo_reclamo (ID_TIPO_RECLAMO,DESCRIPCION) SELECT * FROM LOS_CEBOLLITAS.tipo_reclamo

INSERT INTO LOS_CEBOLLITAS.BI_dia VALUES (1,'DOMINGO')
INSERT INTO LOS_CEBOLLITAS.BI_dia VALUES (2,'LUNES')
INSERT INTO LOS_CEBOLLITAS.BI_dia VALUES (3,'MARTES')
INSERT INTO LOS_CEBOLLITAS.BI_dia VALUES (4,'MIERCOLES')
INSERT INTO LOS_CEBOLLITAS.BI_dia VALUES (5,'JUEVES')
INSERT INTO LOS_CEBOLLITAS.BI_dia VALUES (6,'VIERNES')
INSERT INTO LOS_CEBOLLITAS.BI_dia VALUES (7,'SABADO')

INSERT INTO LOS_CEBOLLITAS.BI_localidad SELECT * FROM LOS_CEBOLLITAS.localidad

INSERT INTO LOS_CEBOLLITAS.BI_estado_reclamo SELECT DISTINCT ESTADO FROM LOS_CEBOLLITAS.reclamo

INSERT INTO LOS_CEBOLLITAS.BI_rango_etario VALUES (0,'<25')
INSERT INTO LOS_CEBOLLITAS.BI_rango_etario VALUES (1,'25-35')
INSERT INTO LOS_CEBOLLITAS.BI_rango_etario VALUES (2,'35-55')
INSERT INTO LOS_CEBOLLITAS.BI_rango_etario VALUES (3,'>55')

INSERT INTO LOS_CEBOLLITAS.BI_rango_horario VALUES (0,'8:00-10:00')
INSERT INTO LOS_CEBOLLITAS.BI_rango_horario VALUES (1,'10:00-12:00')
INSERT INTO LOS_CEBOLLITAS.BI_rango_horario VALUES (2,'12:00-14:00')
INSERT INTO LOS_CEBOLLITAS.BI_rango_horario VALUES (3,'14:00-16:00')
INSERT INTO LOS_CEBOLLITAS.BI_rango_horario VALUES (4,'16:00-18:00')
INSERT INTO LOS_CEBOLLITAS.BI_rango_horario VALUES (5,'18:00-20:00')
INSERT INTO LOS_CEBOLLITAS.BI_rango_horario VALUES (6,'20:00-22:00')
INSERT INTO LOS_CEBOLLITAS.BI_rango_horario VALUES (7,'22:00-00:00')

INSERT INTO LOS_CEBOLLITAS.BI_tiempo (MES,ANIO) 
SELECT DISTINCT MONTH(FECHA_HORA_PEDIDO),YEAR(FECHA_HORA_PEDIDO) 
FROM LOS_CEBOLLITAS.pedidos
WHERE FECHA_HORA_PEDIDO IS NOT NULL
UNION
SELECT DISTINCT MONTH(FECHA_HORA_MENSAJERIA),YEAR(FECHA_HORA_MENSAJERIA)
FROM LOS_CEBOLLITAS.mensajeria
WHERE FECHA_HORA_MENSAJERIA IS NOT NULL
UNION
SELECT DISTINCT MONTH(FECHA_HORA_RECLAMO),YEAR(FECHA_HORA_RECLAMO)
FROM LOS_CEBOLLITAS.reclamo
WHERE FECHA_HORA_RECLAMO IS NOT NULL


INSERT INTO LOS_CEBOLLITAS.BI_hechos_pedidos
(
	ID_DIA,
	ID_ESTADO_PEDIDO,
	ID_LOCAL,
	ID_LOCALIDAD,
	ID_RANGO_ETARIO_USUARIO,
	ID_RANGO_ETARIO_REPARTIDOR,
	ID_RANGO_HORARIO,
	ID_TIEMPO,
	ID_TIPO_LOCAL,
	ID_TIPO_MEDIO,
	ID_TIPO_MOVILIDAD,
	CANT_PEDIDO,
    DESVIO_PROMEDIO,
    MONTO_TOTAL,
    VALOR_PROMEDIO_ENVIO,
    MONTO_CUPONES,
    CALIFICACION,
    PORCENTAJE_ENTREGADOS
)
SELECT day.ID_DIA,
	p.ESTADO_PEDIDO,
	p.ID_LOCAL,
	d.ID_LOCALIDAD,
	(CASE 
		WHEN (2023-YEAR(u.FECHA_NAC)) < 25 THEN 0
		WHEN ((2023-YEAR(u.FECHA_NAC)) >= 25) AND ((2023-YEAR(u.FECHA_NAC)) <= 35) THEN 1
		WHEN ((2023-YEAR(u.FECHA_NAC)) >= 35) AND ((2023-YEAR(u.FECHA_NAC)) <= 55) THEN  2
		ELSE 3
	END) AS RANGO_ETARIO_USUARIO,
	(CASE 
		WHEN (2023-YEAR(r.FECHA_NAC)) < 25 THEN 0
		WHEN ((2023-YEAR(r.FECHA_NAC)) >= 25) AND ((2023-YEAR(r.FECHA_NAC)) <= 35) THEN 1
		WHEN ((2023-YEAR(r.FECHA_NAC)) >= 35) AND ((2023-YEAR(r.FECHA_NAC)) <= 55) THEN  2
		ELSE 3
	END) AS RANGO_ETARIO_REPARTIDOR,
	(CASE 
		WHEN DATEPART(HOUR,p.FECHA_HORA_PEDIDO) BETWEEN 8 AND 10 THEN 0
		WHEN DATEPART(HOUR,p.FECHA_HORA_PEDIDO) BETWEEN 10 AND 12 THEN 1
		WHEN DATEPART(HOUR,p.FECHA_HORA_PEDIDO) BETWEEN 12 AND 14 THEN 2
		WHEN DATEPART(HOUR,p.FECHA_HORA_PEDIDO) BETWEEN 14 AND 16 THEN 3
		WHEN DATEPART(HOUR,p.FECHA_HORA_PEDIDO) BETWEEN 16 AND 18 THEN 4
		WHEN DATEPART(HOUR,p.FECHA_HORA_PEDIDO) BETWEEN 18 AND 20 THEN 5
		WHEN DATEPART(HOUR,p.FECHA_HORA_PEDIDO) BETWEEN 20 AND 22 THEN 6
		WHEN DATEPART(HOUR,p.FECHA_HORA_PEDIDO) BETWEEN 22 AND 00 THEN 7
	END) AS RANGO_HORARIO,
	t.ID_TIEMPO,
	l.ID_TIPO,
	mp.ID_TIPO_PAGO,
	r.ID_TIPO_MOVILIDAD,
	COUNT(DISTINCT p.NRO_PEDIDO) CANT_PEDIDO,
	SUM(DATEDIFF(MI,p.FECHA_HORA_PEDIDO,p.FECHA_HORA_ENTREGA)-p.TIEMPO_ESTIMADO_ENTREGA) DESVIO_PROMEDIO,
	SUM(p.TOTAL_PEDIDO) MONTO_TOTAL,
	SUM(e.PRECIO_ENVIO) PROMEDIO_ENVIO,
	SUM(p.TOTAL_DESCUENTO) MONTO_CUPONES,
	SUM(p.CALIFICACION) CALIFICACION,
	(COUNT(CASE WHEN p.ESTADO_PEDIDO = 2 THEN 1 END) / COUNT(p.NRO_PEDIDO))  * 100 PORCENTAJE_ENTREGADOS
	FROM LOS_CEBOLLITAS.pedidos p
	JOIN LOS_CEBOLLITAS.BI_local l ON p.ID_LOCAL = l.ID_LOCAL
	JOIN LOS_CEBOLLITAS.envio e ON p.ID_ENVIO = e.ID_ENVIO
	JOIN LOS_CEBOLLITAS.direcciones d ON d.ID_DIRECCION = e.DIRECCION_ENVIO
	JOIN LOS_CEBOLLITAS.medio_pago mp ON p.ID_MEDIO_PAGO = mp.ID_MEDIO_PAGO
	JOIN LOS_CEBOLLITAS.repartidor r ON r.ID_REPARTIDOR = e.ID_REPARTIDOR
	JOIN LOS_CEBOLLITAS.BI_dia day ON DATEPART(dw,p.FECHA_HORA_PEDIDO) = day.ID_DIA
	JOIN LOS_CEBOLLITAS.BI_tiempo t ON MONTH(p.FECHA_HORA_PEDIDO) = t.MES AND YEAR(p.FECHA_HORA_PEDIDO) = t.ANIO
	JOIN LOS_CEBOLLITAS.usuario u ON u.ID_USUARIO = p.ID_USUARIO
	GROUP BY day.ID_DIA,
	p.ESTADO_PEDIDO,
	p.ID_LOCAL,
	d.ID_LOCALIDAD,
	t.ID_TIEMPO,
	l.ID_TIPO,
	mp.ID_TIPO_PAGO,
	r.ID_TIPO_MOVILIDAD,
	(CASE 
		WHEN (2023-YEAR(u.FECHA_NAC)) < 25 THEN 0
		WHEN ((2023-YEAR(u.FECHA_NAC)) >= 25) AND ((2023-YEAR(u.FECHA_NAC)) <= 35) THEN 1
		WHEN ((2023-YEAR(u.FECHA_NAC)) >= 35) AND ((2023-YEAR(u.FECHA_NAC)) <= 55) THEN  2
		ELSE 3
	END),
	(CASE 
		WHEN (2023-YEAR(r.FECHA_NAC)) < 25 THEN 0
		WHEN ((2023-YEAR(r.FECHA_NAC)) >= 25) AND ((2023-YEAR(r.FECHA_NAC)) <= 35) THEN 1
		WHEN ((2023-YEAR(r.FECHA_NAC)) >= 35) AND ((2023-YEAR(r.FECHA_NAC)) <= 55) THEN  2
		ELSE 3
	END),
	(CASE 
		WHEN DATEPART(HOUR,p.FECHA_HORA_PEDIDO) BETWEEN 8 AND 10 THEN 0
		WHEN DATEPART(HOUR,p.FECHA_HORA_PEDIDO) BETWEEN 10 AND 12 THEN 1
		WHEN DATEPART(HOUR,p.FECHA_HORA_PEDIDO) BETWEEN 12 AND 14 THEN 2
		WHEN DATEPART(HOUR,p.FECHA_HORA_PEDIDO) BETWEEN 14 AND 16 THEN 3
		WHEN DATEPART(HOUR,p.FECHA_HORA_PEDIDO) BETWEEN 16 AND 18 THEN 4
		WHEN DATEPART(HOUR,p.FECHA_HORA_PEDIDO) BETWEEN 18 AND 20 THEN 5
		WHEN DATEPART(HOUR,p.FECHA_HORA_PEDIDO) BETWEEN 20 AND 22 THEN 6
		WHEN DATEPART(HOUR,p.FECHA_HORA_PEDIDO) BETWEEN 22 AND 00 THEN 7
	END)

INSERT INTO LOS_CEBOLLITAS.BI_hechos_mensajeria
(
	ID_DIA,
	ID_ESTADO_MENSAJERIA,
	ID_LOCALIDAD,
	ID_RANGO_ETARIO_USUARIO,
	ID_RANGO_ETARIO_REPARTIDOR,
	ID_RANGO_HORARIO,
	ID_TIEMPO,
	ID_TIPO_MEDIO,
	ID_TIPO_MOVILIDAD,
	ID_TIPO_PAQUETE,
	DESVIO_PROMEDIO,
	PROMEDIO_VALOR_ASEGURADO,
	PORCENTAJE_ENTREGADOS	
)
SELECT day.ID_DIA,
	m.ID_ESTADO,
	d.ID_LOCALIDAD,
	(CASE 
		WHEN (2023-YEAR(u.FECHA_NAC)) < 25 THEN 0
		WHEN ((2023-YEAR(u.FECHA_NAC)) >= 25) AND ((2023-YEAR(u.FECHA_NAC)) <= 35) THEN 1
		WHEN ((2023-YEAR(u.FECHA_NAC)) >= 35) AND ((2023-YEAR(u.FECHA_NAC)) <= 55) THEN  2
		ELSE 3
	END) AS RANGO_ETARIO_USUARIO,
	(CASE 
		WHEN (2023-YEAR(r.FECHA_NAC)) < 25 THEN 0
		WHEN ((2023-YEAR(r.FECHA_NAC)) >= 25) AND ((2023-YEAR(r.FECHA_NAC)) <= 35) THEN 1
		WHEN ((2023-YEAR(r.FECHA_NAC)) >= 35) AND ((2023-YEAR(r.FECHA_NAC)) <= 55) THEN  2
		ELSE 3
	END) AS RANGO_ETARIO_REPARTIDOR,
	(CASE 
		WHEN DATEPART(HOUR,m.FECHA_HORA_MENSAJERIA) BETWEEN 8 AND 10 THEN 0
		WHEN DATEPART(HOUR,m.FECHA_HORA_MENSAJERIA) BETWEEN 10 AND 12 THEN 1
		WHEN DATEPART(HOUR,m.FECHA_HORA_MENSAJERIA) BETWEEN 12 AND 14 THEN 2
		WHEN DATEPART(HOUR,m.FECHA_HORA_MENSAJERIA) BETWEEN 14 AND 16 THEN 3
		WHEN DATEPART(HOUR,m.FECHA_HORA_MENSAJERIA) BETWEEN 16 AND 18 THEN 4
		WHEN DATEPART(HOUR,m.FECHA_HORA_MENSAJERIA) BETWEEN 18 AND 20 THEN 5
		WHEN DATEPART(HOUR,m.FECHA_HORA_MENSAJERIA) BETWEEN 20 AND 22 THEN 6
		WHEN DATEPART(HOUR,m.FECHA_HORA_MENSAJERIA) BETWEEN 22 AND 00 THEN 7
	END) AS RANGO_HORARIO,
	t.ID_TIEMPO,
	mp.ID_TIPO_PAGO,
	r.ID_TIPO_MOVILIDAD,
	m.TIPO_PAQUETE,
	SUM(DATEDIFF(MI,m.FECHA_HORA_MENSAJERIA,m.FECHA_HORA_ENTREGA)) DESVIO_PROMEDIO,
	SUM(m.VALOR_ASEGURADO) VALOR_ASEGURADO_PROMEDIO,
	(COUNT(CASE WHEN m.ID_ESTADO = 2 THEN 1 END) / COUNT(m.NRO_MENSAJERIA))  * 100 PORCENTAJE_ENTREGADOS
	FROM LOS_CEBOLLITAS.mensajeria m
	JOIN LOS_CEBOLLITAS.direcciones d ON d.DIRECCION = m.DIR_ORIGEN
	JOIN LOS_CEBOLLITAS.medio_pago mp ON m.ID_MEDIO_PAGO = mp.ID_MEDIO_PAGO
	JOIN LOS_CEBOLLITAS.repartidor r ON r.ID_REPARTIDOR = m.ID_REPARTIDOR
	JOIN LOS_CEBOLLITAS.BI_dia day ON DATEPART(dw,m.FECHA_HORA_MENSAJERIA) = day.ID_DIA
	JOIN LOS_CEBOLLITAS.BI_tiempo t ON MONTH(m.FECHA_HORA_MENSAJERIA) = t.MES AND YEAR(m.FECHA_HORA_MENSAJERIA) = t.ANIO
	JOIN LOS_CEBOLLITAS.usuario u ON u.ID_USUARIO = m.ID_USUARIO
	GROUP BY
	day.ID_DIA,
	m.ID_ESTADO,
	d.ID_LOCALIDAD,
	(CASE 
		WHEN (2023-YEAR(u.FECHA_NAC)) < 25 THEN 0
		WHEN ((2023-YEAR(u.FECHA_NAC)) >= 25) AND ((2023-YEAR(u.FECHA_NAC)) <= 35) THEN 1
		WHEN ((2023-YEAR(u.FECHA_NAC)) >= 35) AND ((2023-YEAR(u.FECHA_NAC)) <= 55) THEN  2
		ELSE 3
	END),
	(CASE 
		WHEN (2023-YEAR(r.FECHA_NAC)) < 25 THEN 0
		WHEN ((2023-YEAR(r.FECHA_NAC)) >= 25) AND ((2023-YEAR(r.FECHA_NAC)) <= 35) THEN 1
		WHEN ((2023-YEAR(r.FECHA_NAC)) >= 35) AND ((2023-YEAR(r.FECHA_NAC)) <= 55) THEN  2
		ELSE 3
	END),
	(CASE 
		WHEN DATEPART(HOUR,m.FECHA_HORA_MENSAJERIA) BETWEEN 8 AND 10 THEN 0
		WHEN DATEPART(HOUR,m.FECHA_HORA_MENSAJERIA) BETWEEN 10 AND 12 THEN 1
		WHEN DATEPART(HOUR,m.FECHA_HORA_MENSAJERIA) BETWEEN 12 AND 14 THEN 2
		WHEN DATEPART(HOUR,m.FECHA_HORA_MENSAJERIA) BETWEEN 14 AND 16 THEN 3
		WHEN DATEPART(HOUR,m.FECHA_HORA_MENSAJERIA) BETWEEN 16 AND 18 THEN 4
		WHEN DATEPART(HOUR,m.FECHA_HORA_MENSAJERIA) BETWEEN 18 AND 20 THEN 5
		WHEN DATEPART(HOUR,m.FECHA_HORA_MENSAJERIA) BETWEEN 20 AND 22 THEN 6
		WHEN DATEPART(HOUR,m.FECHA_HORA_MENSAJERIA) BETWEEN 22 AND 00 THEN 7
	END),
	t.ID_TIEMPO,
	mp.ID_TIPO_PAGO,
	r.ID_TIPO_MOVILIDAD,
	m.TIPO_PAQUETE

INSERT INTO LOS_CEBOLLITAS.BI_hechos_reclamos
(
	ID_DIA,
	ID_ESTADO_RECLAMO,
	ID_LOCAL,
	ID_LOCALIDAD,
	ID_RANGO_ETARIO_OPERADOR,
	ID_RANGO_ETARIO_REPARTIDOR,
	ID_RANGO_ETARIO_USUARIO,
	ID_RANGO_HORARIO,
	ID_TIEMPO,
	ID_TIPO_LOCAL,
	ID_TIPO_MEDIO,
	ID_TIPO_MOVILIDAD,
	ID_TIPO_RECLAMO,
	PROMEDIO_RESOLUCION,
	CANT_RECLAMOS,
	MONTO_GENERADO
)
SELECT day.ID_DIA,
	er.ID_ESTADO_RECLAMO,
	l.ID_LOCAL,
	d.ID_LOCALIDAD,
	(CASE 
		WHEN (2023-YEAR(op.FECHA_NAC)) < 25 THEN 0
		WHEN ((2023-YEAR(op.FECHA_NAC)) >= 25) AND ((2023-YEAR(op.FECHA_NAC)) <= 35) THEN 1
		WHEN ((2023-YEAR(op.FECHA_NAC)) >= 35) AND ((2023-YEAR(op.FECHA_NAC)) <= 55) THEN  2
		ELSE 3
	END) AS RANGO_ETARIO_OPERADOR,
	(CASE 
		WHEN (2023-YEAR(rep.FECHA_NAC)) < 25 THEN 0
		WHEN ((2023-YEAR(rep.FECHA_NAC)) >= 25) AND ((2023-YEAR(rep.FECHA_NAC)) <= 35) THEN 1
		WHEN ((2023-YEAR(rep.FECHA_NAC)) >= 35) AND ((2023-YEAR(rep.FECHA_NAC)) <= 55) THEN  2
		ELSE 3
	END) AS RANGO_ETARIO_REPARTIDOR,
	(CASE 
		WHEN (2023-YEAR(u.FECHA_NAC)) < 25 THEN 0
		WHEN ((2023-YEAR(u.FECHA_NAC)) >= 25) AND ((2023-YEAR(u.FECHA_NAC)) <= 35) THEN 1
		WHEN ((2023-YEAR(u.FECHA_NAC)) >= 35) AND ((2023-YEAR(u.FECHA_NAC)) <= 55) THEN  2
		ELSE 3
	END) AS RANGO_ETARIO_USUARIO,
	(CASE 
		WHEN DATEPART(HOUR,r.FECHA_HORA_RECLAMO) BETWEEN 8 AND 10 THEN 0
		WHEN DATEPART(HOUR,r.FECHA_HORA_RECLAMO) BETWEEN 10 AND 12 THEN 1
		WHEN DATEPART(HOUR,r.FECHA_HORA_RECLAMO) BETWEEN 12 AND 14 THEN 2
		WHEN DATEPART(HOUR,r.FECHA_HORA_RECLAMO) BETWEEN 14 AND 16 THEN 3
		WHEN DATEPART(HOUR,r.FECHA_HORA_RECLAMO) BETWEEN 16 AND 18 THEN 4
		WHEN DATEPART(HOUR,r.FECHA_HORA_RECLAMO) BETWEEN 18 AND 20 THEN 5
		WHEN DATEPART(HOUR,r.FECHA_HORA_RECLAMO) BETWEEN 20 AND 22 THEN 6
		WHEN DATEPART(HOUR,r.FECHA_HORA_RECLAMO) BETWEEN 22 AND 00 THEN 7
	END) AS RANGO_HORARIO,
	t.ID_TIEMPO,
	l.ID_TIPO,
	mp.ID_TIPO_PAGO,
	rep.ID_TIPO_MOVILIDAD,
	r.ID_TIPO_RECLAMO,
	SUM(DATEDIFF(MI,r.FECHA_HORA_RECLAMO,r.FECHA_HORA_SOLUCION)) PROMEDIO_RESOLUCION,
	COUNT(DISTINCT r.NRO_RECLAMO) CANT_RECLAMOS,
	SUM(ISNULL(c.MONTO,0)) MONTO_GENERADO
	FROM LOS_CEBOLLITAS.reclamo r
	JOIN LOS_CEBOLLITAS.BI_dia day ON DATEPART(dw,r.FECHA_HORA_RECLAMO) = day.ID_DIA
	JOIN LOS_CEBOLLITAS.BI_estado_reclamo er ON er.ESTADO_RECLAMO = r.ESTADO
	JOIN LOS_CEBOLLITAS.pedidos p ON p.NRO_PEDIDO = r.NRO_PEDIDO
	JOIN LOS_CEBOLLITAS.local l ON l.ID_LOCAL = p.ID_LOCAL
	JOIN LOS_CEBOLLITAS.medio_pago mp ON p.ID_MEDIO_PAGO = mp.ID_MEDIO_PAGO
	JOIN LOS_CEBOLLITAS.direcciones d ON l.ID_DIRECCION = d.ID_DIRECCION
	JOIN LOS_CEBOLLITAS.usuario u ON u.ID_USUARIO = r.ID_USUARIO
	JOIN LOS_CEBOLLITAS.envio e ON e.ID_ENVIO = p.ID_ENVIO
	JOIN LOS_CEBOLLITAS.repartidor rep ON rep.ID_REPARTIDOR = e.ID_REPARTIDOR
	JOIN LOS_CEBOLLITAS.operador_reclamo op ON op.ID_OPERADOR = r.ID_OPERADOR
	JOIN LOS_CEBOLLITAS.BI_tiempo t ON MONTH(r.FECHA_HORA_RECLAMO) = t.MES AND YEAR(r.FECHA_HORA_RECLAMO) = t.ANIO
	JOIN LOS_CEBOLLITAS.reclamo_cupon rc ON rc.ID_RECLAMO_CUPON = r.ID_RECLAMO
	JOIN LOS_CEBOLLITAS.cupon c ON c.NRO_CUPON = rc.NRO_CUPON_RECLAMO
	GROUP BY day.ID_DIA,
	er.ID_ESTADO_RECLAMO,
	l.ID_LOCAL,
	d.ID_LOCALIDAD,
	(CASE 
		WHEN (2023-YEAR(op.FECHA_NAC)) < 25 THEN 0
		WHEN ((2023-YEAR(op.FECHA_NAC)) >= 25) AND ((2023-YEAR(op.FECHA_NAC)) <= 35) THEN 1
		WHEN ((2023-YEAR(op.FECHA_NAC)) >= 35) AND ((2023-YEAR(op.FECHA_NAC)) <= 55) THEN  2
		ELSE 3
	END),
	(CASE 
		WHEN (2023-YEAR(rep.FECHA_NAC)) < 25 THEN 0
		WHEN ((2023-YEAR(rep.FECHA_NAC)) >= 25) AND ((2023-YEAR(rep.FECHA_NAC)) <= 35) THEN 1
		WHEN ((2023-YEAR(rep.FECHA_NAC)) >= 35) AND ((2023-YEAR(rep.FECHA_NAC)) <= 55) THEN  2
		ELSE 3
	END),
	(CASE 
		WHEN (2023-YEAR(u.FECHA_NAC)) < 25 THEN 0
		WHEN ((2023-YEAR(u.FECHA_NAC)) >= 25) AND ((2023-YEAR(u.FECHA_NAC)) <= 35) THEN 1
		WHEN ((2023-YEAR(u.FECHA_NAC)) >= 35) AND ((2023-YEAR(u.FECHA_NAC)) <= 55) THEN  2
		ELSE 3
	END),
	(CASE 
		WHEN DATEPART(HOUR,r.FECHA_HORA_RECLAMO) BETWEEN 8 AND 10 THEN 0
		WHEN DATEPART(HOUR,r.FECHA_HORA_RECLAMO) BETWEEN 10 AND 12 THEN 1
		WHEN DATEPART(HOUR,r.FECHA_HORA_RECLAMO) BETWEEN 12 AND 14 THEN 2
		WHEN DATEPART(HOUR,r.FECHA_HORA_RECLAMO) BETWEEN 14 AND 16 THEN 3
		WHEN DATEPART(HOUR,r.FECHA_HORA_RECLAMO) BETWEEN 16 AND 18 THEN 4
		WHEN DATEPART(HOUR,r.FECHA_HORA_RECLAMO) BETWEEN 18 AND 20 THEN 5
		WHEN DATEPART(HOUR,r.FECHA_HORA_RECLAMO) BETWEEN 20 AND 22 THEN 6
		WHEN DATEPART(HOUR,r.FECHA_HORA_RECLAMO) BETWEEN 22 AND 00 THEN 7
	END),
	t.ID_TIEMPO,
	l.ID_TIPO,
	mp.ID_TIPO_PAGO,
	rep.ID_TIPO_MOVILIDAD,
	r.ID_TIPO_RECLAMO

END;
GO

EXEC LOS_CEBOLLITAS.MigrarDatosBI
GO

CREATE VIEW dia_y_horario_mayor_pedidos
AS
WITH pedidos_cantidad AS (
    SELECT
        L.NOMBRE AS LOCALIDAD,
		tp.TIPO_LOCAL,
        LH.MES,
        LH.ANIO,
        DH.DIA,
        RH.RANGO_HORARIO,
        HP.CANT_PEDIDO,
        ROW_NUMBER() OVER (PARTITION BY L.NOMBRE, loc.CATEGORIA, LH.MES, LH.ANIO
                           ORDER BY HP.CANT_PEDIDO DESC) AS RN
    FROM
        LOS_CEBOLLITAS.BI_hechos_pedidos AS HP
        JOIN LOS_CEBOLLITAS.BI_tiempo AS LH ON HP.ID_TIEMPO = LH.ID_TIEMPO
		JOIN LOS_CEBOLLITAS.BI_localidad L ON L.ID_LOCALIDAD = HP.ID_LOCALIDAD
		JOIN LOS_CEBOLLITAS.BI_local loc ON loc.ID_LOCAL = HP.ID_LOCAL
		JOIN LOS_CEBOLLITAS.BI_tipo_local tp ON tp.ID_TIPO_LOCAL = loc.ID_TIPO
        JOIN LOS_CEBOLLITAS.BI_dia AS DH ON HP.ID_DIA = DH.ID_DIA
        JOIN LOS_CEBOLLITAS.BI_rango_horario AS RH ON HP.ID_RANGO_HORARIO = RH.ID_RANGO_HORARIO
)
SELECT
    LOCALIDAD,
	TIPO_LOCAL
    MES,
    ANIO,
    DIA,
    RANGO_HORARIO,
    CANT_PEDIDO AS MAX_CANT_PEDIDO
FROM
    pedidos_cantidad
WHERE
    RN = 1;
GO

CREATE VIEW monto_total_no_cobrado 
AS
SELECT SUM(MONTO_TOTAL) MONTO,ID_LOCAL,ID_DIA,ID_RANGO_HORARIO FROM LOS_CEBOLLITAS.BI_hechos_pedidos
WHERE ID_ESTADO_PEDIDO = 3
GROUP BY ID_LOCAL,ID_DIA,ID_RANGO_HORARIO
GO

CREATE VIEW valor_envio_promedio
AS
SELECT AVG(VALOR_PROMEDIO_ENVIO) VALOR_ENVIO_PROMEDIO,t.MES,ID_LOCALIDAD FROM LOS_CEBOLLITAS.BI_hechos_pedidos p
JOIN LOS_CEBOLLITAS.BI_tiempo t ON t.ID_TIEMPO = p.ID_TIEMPO
GROUP BY t.MES,ID_LOCALIDAD
GO

CREATE VIEW desvio_promedio
AS
SELECT AVG(DESVIO_PROMEDIO) DESVIO_PROMEDIO,ID_TIPO_MOVILIDAD,ID_DIA,ID_RANGO_HORARIO FROM LOS_CEBOLLITAS.BI_hechos_pedidos p
GROUP BY ID_TIPO_MOVILIDAD,ID_DIA,ID_RANGO_HORARIO
UNION
SELECT AVG(DESVIO_PROMEDIO) DESVIO_PROMEDIO,ID_TIPO_MOVILIDAD,ID_DIA,ID_RANGO_HORARIO FROM LOS_CEBOLLITAS.BI_hechos_mensajeria m
GROUP BY ID_TIPO_MOVILIDAD,ID_DIA,ID_RANGO_HORARIO
GO

CREATE VIEW monto_cupones
AS
SELECT SUM(MONTO_CUPONES) MONTO_CUPONES,t.MES,ID_RANGO_ETARIO_USUARIO FROM LOS_CEBOLLITAS.BI_hechos_pedidos p
JOIN LOS_CEBOLLITAS.BI_tiempo t ON t.ID_TIEMPO = p.ID_TIEMPO
GROUP BY t.MES,ID_RANGO_ETARIO_USUARIO
GO

CREATE VIEW calificacion_promedio
AS
SELECT AVG(CALIFICACION) CALIFICAION_PROMEDIO,t.MES,ID_LOCAL FROM LOS_CEBOLLITAS.BI_hechos_pedidos p
JOIN LOS_CEBOLLITAS.BI_tiempo t ON t.ID_TIEMPO = p.ID_TIEMPO
GROUP BY t.MES,ID_LOCAL
GO

CREATE VIEW porcentaje_entregados
AS
SELECT SUM(PORCENTAJE_ENTREGADOS)/COUNT(CANT_PEDIDO) PORCENTAJE_ENTREGADOS,t.MES,ID_LOCALIDAD,ID_RANGO_ETARIO_REPARTIDOR FROM LOS_CEBOLLITAS.BI_hechos_pedidos p
JOIN LOS_CEBOLLITAS.BI_tiempo t ON t.ID_TIEMPO = p.ID_TIEMPO
GROUP BY t.MES,ID_LOCALIDAD,ID_RANGO_ETARIO_REPARTIDOR
UNION
SELECT SUM(PORCENTAJE_ENTREGADOS)/COUNT(*),t.MES,ID_LOCALIDAD,ID_RANGO_ETARIO_REPARTIDOR FROM LOS_CEBOLLITAS.BI_hechos_mensajeria m
JOIN LOS_CEBOLLITAS.BI_tiempo t ON t.ID_TIEMPO = m.ID_TIEMPO
GROUP BY t.MES,ID_LOCALIDAD,ID_RANGO_ETARIO_REPARTIDOR
GO

CREATE VIEW promedio_valor_asegurado
AS
SELECT AVG(PROMEDIO_VALOR_ASEGURADO) PROMEDIO_VALOR_ASEGURADO,t.MES,ID_TIPO_PAQUETE FROM LOS_CEBOLLITAS.BI_hechos_mensajeria m
JOIN LOS_CEBOLLITAS.BI_tiempo t ON t.ID_TIEMPO = m.ID_TIEMPO
GROUP BY t.MES,ID_TIPO_PAQUETE
GO

CREATE VIEW cant_reclamos_recibidos
AS
SELECT SUM(CANT_RECLAMOS) CANT_RECLAMOS,t.MES,ID_LOCAL,ID_DIA,ID_RANGO_HORARIO FROM LOS_CEBOLLITAS.BI_hechos_reclamos r
JOIN LOS_CEBOLLITAS.BI_tiempo t ON t.ID_TIEMPO = r.ID_TIEMPO
GROUP BY t.MES,ID_LOCAL,ID_DIA,ID_RANGO_HORARIO
GO

CREATE VIEW tiempo_resolucion_reclamo
AS
SELECT AVG(PROMEDIO_RESOLUCION) TIEMPO_PROMEDIO,t.MES,ID_TIPO_RECLAMO,ID_RANGO_ETARIO_OPERADOR FROM LOS_CEBOLLITAS.BI_hechos_reclamos r
JOIN LOS_CEBOLLITAS.BI_tiempo t ON t.ID_TIEMPO = r.ID_TIEMPO
GROUP BY t.MES,ID_TIPO_RECLAMO,ID_RANGO_ETARIO_OPERADOR
GO

CREATE VIEW monto_cupones_por_reclamo
AS
SELECT SUM(MONTO_GENERADO) MONTO_GENERADO,t.MES,t.ANIO FROM LOS_CEBOLLITAS.BI_hechos_reclamos r
JOIN LOS_CEBOLLITAS.BI_tiempo t ON t.ID_TIEMPO = r.ID_TIEMPO
GROUP BY t.MES,t.ANIO
GO